### ISSUE TITLE
能否添加RC4-MD5支持

### ISSUE THREAD

**Issue by youdeoo** [hacking001/x2tap#13]
SS添加RC4-MD5加密方式

**Comment by hacking001** [comment]
@youdeoo 抱歉，当前无法给 Shadowsocks 添加 RC4-MD5 加密方式的支持！

因为当前 x2tap 是依赖 v2ray-core 来支持 Shadowsocks 的，然而 v2ray-core 的 Shadowsocks 不支持这个加密方式我也没有办法

可以上 v2ray-core 发 issue 让他们支持这个加密方式，这样我就能添加了
