### ISSUE TITLE
无法通过V2ray订阅链接获取配置

### ISSUE THREAD

**Issue by nita0318** [hacking001/x2tap#14]
---------------------------
错误
---------------------------
在处理订阅链接："" 时发生错误：System.NotSupportedException: 不支持的伪装类型：chacha20-poly1305

   在 x2tap.Utils.Parse.v2ray(String text)

   在 x2tap.View.SubscribeForm.SubscribeLinksButton_Click(Object sender, EventArgs e)

是否终止导入？
---------------------------
是(Y)   否(N)   
---------------------------
应该是加密方式被识别为伪装类型的缘故
版本0.2.0

**Comment by hacking001** [comment]
@nita0318 感谢反馈，将会尽快开始问题跟踪

**Comment by hacking001** [comment]
@nita0318 我这里在 v2rayNG 上导出一个为 chacha20-poly1305 的代理，在导入到 x2tap 时并没有发生这样的错误。

方便放一下您的 vmess:// 链接吗？（自行修改服务器地址）

**Comment by hacking001** [comment]
@nita0318 为什么加密方式会被解析成伪装类型呢，VMess 分享链接压根就没有加密方式这个字段啊 😂

**Comment by nita0318** [comment]
链接：
vmess://eyJwcyI6IlBsdXMiLCJhZGQiOiI0OC42NC4xOTIuMTM2IiwicG9ydCI6IjY3MDgiLCJpZCI6IjAyMDY2M2M3LTYzM2YtNjMzZi02M2M3LTE3NTg5ZjVkNTA2MSIsImFpZCI6IjIiLCJuZXQiOiJ0Y3AiLCJ0eXBlIjoiY2hhY2hhMjAtcG9seTEzMDUiLCJob3N0IjoiIiwidGxzIjoiIn0=
![捕获](https://user-images.githubusercontent.com/49789145/56432162-fdc0d880-62fe-11e9-9783-406593c4e946.PNG)
V2rayN 2.27导入后：
![捕获1](https://user-images.githubusercontent.com/49789145/56432168-02858c80-62ff-11e9-9929-108acac801b1.PNG)

**Comment by hacking001** [comment]
@nita0318 你这个链接有问题，在 v2rayN 导入后重新导出，再放 x2tap 吧

**Comment by hacking001** [comment]
@nita0318 很明显是一条不符合规范的链接，v2rayN 都没有处理上那个 chacha20-poly1305
