### ISSUE TITLE
日志怎么看?

### ISSUE THREAD

**Issue by wxlg1117** [hacking001/x2tap#19]
配置的55R服务器ip局域网的另外一个ip(用了kcptun加速),启动过程似乎正常,
![Snipaste_2019-05-08_00-25-07](https://user-images.githubusercontent.com/9752596/57285617-2b22ca00-70e6-11e9-8564-95c9012efe3e.png)

访问国内网络正常,无法访问google这些,另外那个速度显示似乎也不正常

**Comment by hacking001** [comment]
@wxlg1117 - 日志没搞 ...
- 流量统计由 Windows 完成

**Comment by hacking001** [comment]
@wxlg1117 启动后在命令行执行 ROUTE PRINT -4 看看

**Comment by hacking001** [comment]
请尝试 [1.0.0-BETA](https://github.com/hacking001/x2tap/releases/tag/1.0.0-BETA)

这个 issue 就先关闭上吧
