### ISSUE TITLE
rejected  v2ray: invalid user

### ISSUE THREAD

**Issue by youliso** [hacking001/x2tap#2]

**Comment by youliso** [comment]
通过 文本 导入 vmess    无效用户 UUID 和 Alter ID  没问题

**Comment by hacking001** [comment]
请详细叙述问题情况

是导入出了问题么

**Comment by youliso** [comment]
导入的话 TLS我没开启 还是会自动勾选       我刚刚试了手动输入还是提示 无效用户

**Comment by youliso** [comment]
找到原因了  我用的 https://github.com/Jrohy/multi-v2ray 的一键脚本 生成的vmess   无效

**Comment by youliso** [comment]
外置规则如何挂载

**Comment by hacking001** [comment]
外置规则啊，还没做上去

**Comment by youliso** [comment]
还有就是内置 绕过局域网和中国 规则 youtube 无法访问

**Comment by hacking001** [comment]
这么恐怖的么？可能是 DNS 污染问题

**Comment by youliso** [comment]
我给你发个规则

**Comment by youliso** [comment]
https://github.com/FQrabbit/SSTap-Rule

**Comment by youliso** [comment]
可以 用这里面的规则

**Comment by hacking001** [comment]
将会最大程度的兼容 SSTap 的规则

**Comment by hacking001** [comment]
很显然，我并不想让 SSTap 的规则直接可以用于 x2tap 上

**Comment by hacking001** [comment]
已经在 x2tap 中加入了外置规则的支持，最大程度兼容了 SSTap

如果创建规则参见：[MODE.md](https://github.com/hacking001/x2tap/blob/master/docs/zh-CN/MODE.md)
样本参见 [Telegram.txt](https://github.com/hacking001/x2tap/blob/master/modes/Telegram.txt)

欢迎提交新规则 PR

**Comment by youliso** [comment]
启动一直报 “检测v2ray 启动失败”

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Friday, April 5, 2019 9:05:48 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


已经在 x2tap 中加入了外置规则的支持，最大程度兼容了 SSTap

如果创建规则参见：MODE.md<https://github.com/hacking001/x2tap/blob/master/docs/zh-CN/MODE.md>
样本参见 Telegram.txt<https://github.com/hacking001/x2tap/blob/master/modes/Telegram.txt>

欢迎提交新规则 PR

―

**Comment by hacking001** [comment]
哪个版本

**Comment by youliso** [comment]
0.0.10 版本

0.0.6以下版本 好着    还有  外置规则中文乱花

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 5:40:30 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


哪个版本

―

**Comment by hacking001** [comment]
外置规则需要 UTF-8 编码保存，0.0.10 是因为内置 DNS 服务了，你是不是机器上有什么程序占着 53 端口

**Comment by hacking001** [comment]
53 端口由 v2ray 的 DNS 服务占着，没法改，如果其他程序占着 53 就会导致 v2ray 启动失败

**Comment by hacking001** [comment]
你自己检查一下吧，我自己干净的开发机是没问题的。

UDP/53、TCP/2810、TCP/2811 这些都是 v2ray 会监听的，如果被其他程序占用了就启动失败！

**Comment by youliso** [comment]
5353 端口也是吗


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 5:45:03 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


你自己检查一下吧，我自己干净的开发机是没问题的。

UDP/53、TCP/2810、TCP/2811 这些都是 v2ray 会监听的，如果被其他程序占用了就启动失败！

―

**Comment by hacking001** [comment]
53 端口不占的

**Comment by hacking001** [comment]
5353 端口不占的，占 UDP/53、TCP/2810、TCP/2811

**Comment by youliso** [comment]
看了下  没有占用53端口

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 5:47:28 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


5353 端口不占的，占 UDP/53、TCP/2810、TCP/2811

―

**Comment by hacking001** [comment]
CMD 进入 x2tap 所在的目录，然后执行 `.\v2ray.exe -config v2ray.txt` 看看

**Comment by youliso** [comment]
不行

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 5:51:37 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


CMD 进入 x2tap 所在的目录，然后执行 .\v2ray.exe -config v2ray.txt 看看

―

**Comment by hacking001** [comment]
报错信息粘上来看看

**Comment by hacking001** [comment]
看那个命令是不是说端口问题，如果是端口问题就是你的问题

如果报配置文件问题就是我的问题

最近给 x2tap 换了新的配置文件生成器，不稳定，可能生成出来有问题的配置

**Comment by youliso** [comment]
没有生成日志文件

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 6:03:29 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


看那个命令是不是说端口问题，如果是端口问题就是你的问题

如果报配置文件问题就是我的问题

最近给 x2tap 换了新的配置文件生成器，不稳定，可能生成出来有问题的配置

―

**Comment by hacking001** [comment]
命令输出什么啊

**Comment by hacking001** [comment]
日志文件在 logging 文件夹里，那里也应该会有些什么吧

**Comment by youliso** [comment]
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to read config file: v2ray.txt > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: Failed to build TCP config. > v2ray.com/core/infra/conf: invalid TCP header config > v2ray.com/core/infra/conf: type not found in JSON context

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 6:06:28 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


日志文件在 logging 文件夹里，那里也应该会有些什么吧

―

**Comment by hacking001** [comment]
配置文件有问题，我的锅，把你的服务器配置发出来。自行隐去地址，其他的一致

**Comment by youliso** [comment]
我用的是https://github.com/sprov065/sprov-ui的一键配置

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 6:09:08 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


配置文件有问题，我的锅，把你的服务器配置发出来。自行隐去地址，其他的一致

―

**Comment by hacking001** [comment]
我指的是 vmess 分享链接

**Comment by hacking001** [comment]
或者你在 x2tap 里点编辑，截图就行

**Comment by youliso** [comment]
[{"Address":"x.x.x.x","AlterID":64,"EncryptMethod":0,"FakeDomain":"","FakeType":0,"Path":"/","Port":xxxx,"Remark":"xx","TLSSecure":false,"TransferProtocol":0,"UserID":"a8818287-f615-4b52-a372-6df8e4ef8947"}]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 6:18:02 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


或者你在 x2tap 里点编辑，截图就行

―

**Comment by hacking001** [comment]
好的，我现在在外面，将会很快展开分析工作

话说这个问题为什么不新开一个 issue 呢

**Comment by youliso** [comment]
我也在外面 发发邮件还可以

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用


________________________________
发件人: Holli_Freed <notifications@github.com>
发送时间: Sunday, April 7, 2019 6:22:19 PM
收件人: hacking001/x2tap
抄送: youliso; Comment
主题: Re: [hacking001/x2tap] rejected v2ray: invalid user (#2)


好的，我现在在外面，将会很快展开分析工作

话说这个问题为什么不新开一个 issue 呢

―

**Comment by hacking001** [comment]
2333333

**Comment by hacking001** [comment]
新版下载：[0.0.11-TESTING](https://github.com/hacking001/x2tap/releases/tag/0.0.11-TESTING)

**Comment by hacking001** [comment]
我本地不报配置文件错误了，出于时间原因没有再做深入的测试（游戏中）
