### ISSUE TITLE
小红伞报毒

### ISSUE THREAD

**Issue by RlLOk6ADk** [hacking001/x2tap#20]
ssr-local.exe文件被Avira识别为TR/Crypt.XPACK.Gen [Torgan]形式，会被自动清除。

**Comment by hacking001** [comment]
@RlLOk6ADk ssr-local.exe 由 @Amazing_DM 提供

**Comment by AmazingDM** [comment]
如觉得有问题 请自行编译 https://github.com/shadowsocksrr/shadowsocksr-libev/tree/Akkariiin/develop
