### ISSUE TITLE
Unable to add SOCKS5 proxy

### ISSUE THREAD

**Issue by WordlessEcho** [hacking001/x2tap#22]
1. Click add server
2. Click add a SOCKS5 server
3. Nothing happened

**Comment by hacking001** [comment]
I'm sorry, the add Socks5 button is just a fixture at the moment.

**Comment by hacking001** [comment]
#5

**Comment by hacking001** [comment]
新版已经加入 Socks5 支持，还有一些问题所以暂未发布至 releases 中
