### ISSUE TITLE
Hardcode Localhost IP into Global Ignore List

### ISSUE THREAD

**Issue by Riajyuu** [hacking001/x2tap#25]
This shall include localhost, 127.0.0.1, ::1 and all ports of them.

**Comment by hacking001** [comment]
See [L529](https://github.com/hacking001/x2tap/blob/master/x2tap/Forms/MainForm.cs#L529) and [L538](https://github.com/hacking001/x2tap/blob/master/x2tap/Forms/MainForm.cs#L538)

**Comment by hacking001** [comment]
By default, loopback IPs ignored.

**Comment by hacking001** [comment]
I tested the direct Socks5 SSR on the local machine (127.0.0.1), no problem (you need to add the server IP on the SSR to the bypass IP list first)

**Comment by Riajyuu** [comment]
1. this seems not include ::1
2. some ports other than 1080 are proxied instead of ignored (actually all ports under local TCP/UDP shall be ignored). e.g. KeePass RPC uses 12356 and NPM Web Services uses 1841.

**Comment by hacking001** [comment]
1. IPv6 will not be processed

2. The system has a default loopback processing routing rule, and my program also has a routing rule setting that ignores the loopback address.
```
        127.0.0.0        255.0.0.0            On link         127.0.0.1    331
        127.0.0.1  255.255.255.255            On link         127.0.0.1    331
  255.255.255.255  255.255.255.255            On link         127.0.0.1    331
```

So, there is no problem with the destination address being the proxy for the loopback addresses.

**Comment by hacking001** [comment]
By default, Loopback addresses is ignored.
