### ISSUE TITLE
Multiple subscription links cannot be added，but this is better than v2rayN.Thanks

### ISSUE THREAD

**Issue by Felix-felix** [hacking001/x2tap#3]

**Comment by hacking001** [comment]
aha ?

ok, i will begin debugging ...

**Comment by hacking001** [comment]
I'm going to start working after my gaming and I just got home from school.

**Comment by hacking001** [comment]
Feature added in [0.0.5-TESTING](https://github.com/hacking001/x2tap/releases/tag/0.0.5-TESTING).

Please try it.

**Comment by Felix-felix** [comment]
Thanks
