### ISSUE TITLE
After adding the subscription link,I have to reboot to see the configration information.Can you set it to automatic reboot? And can I share this in a website that the url is www.coolapk.com?

### ISSUE THREAD

**Issue by Felix-felix** [hacking001/x2tap#4]

**Comment by Felix-felix** [comment]
Another problem is that the sofyware can't be minimized to pallets in win10.

**Comment by Felix-felix** [comment]
虽然能同时添加多个订阅链接，但是不能同时在配置信息那看到其他订阅的代理，只能看到其中一个订阅

**Comment by hacking001** [comment]
- 关于多个订阅导入之后只有一个的问题：我刚刚审查了代码，我似乎忘记了什么，非常抱歉，将会很快改进
- 欢迎分享此项目给他人（另外我也玩酷安，ID：Holli_Freed）
- 目前 x2tap 没有加入任务栏通知图标支持，不过你提了，我就会很快的更新

**Comment by hacking001** [comment]
另外，能用中文为什么不直接用中文发呢。我英语不是很好，难翻译的啊 🤔

**Comment by hacking001** [comment]
订阅更新后程序不会自动更新主界面的列表，这个问题也许已经修复了（我没有测试）

新版下载：[0.0.7-TESTING](https://github.com/hacking001/x2tap/releases/tag/0.0.7-TESTING)

**Comment by hacking001** [comment]
已支持最小化到托盘：[0.1.4-TESTING](https://github.com/hacking001/x2tap/releases/tag/0.1.4-TESTING)
