### ISSUE TITLE
在内置规则的情况下在本地使用udp2raw类工具产生代理回环的问题

### ISSUE THREAD

**Issue by Bourshevik0** [hacking001/x2tap#5]
如果大佬有用过sstap的话，应该知道sstap有一个例外IP功能，可以在使用内置规则的情况下再添加一些例外IP，使得这些例外IP在内置规则模式下直连而非代理。虽然这个从软件逻辑上来讲是有点矛盾，毕竟已经允许大家使用外置规则，再在内置规则的模式下添加例外IP会有点冗余，但是在实际应用场景中会遇到有些游戏的规则无法提取，需要使用全局规则替代使用的情况，此时如果想要在本地使用外部代理工具，譬如[udp2raw](https://www.moerats.com/archives/662/)时会产生代理回环，即本地运行的udp2raw无法访问到远端服务器。

顺便简单说明一下sstap使用udp2raw这类工具的原理，sstap代理启动之后，将ss流量转发给本地的udp2raw类工具的本地接收端口，本地的udp2raw类工具将ss流量处理后，再转发到远端服务器的udp2raw类工具对应端口上，类似的流程在远端服务器重复一遍，以达到代理的目的。

而代理回环的原因就是本地udp2raw类工具转发到远端时，其流量又被x2tap之类的全局代理工具拦截导致的，此时如果放行udp2raw类工具的流量，就可以完成代理过程。

解决的方案有两种，一种是类似sstap那样，添加一个例外IP功能，使得访问这些IP的流量直连远端服务器而非被代理，只是GUI界面写规则对用户而言很麻烦，而且我觉得开发起来也未必简单（table widget警告）。另一种我觉得可能相对简单一些，允许在加载内置规则之后，再加载外部规则，这样用户只要把需要直连的IP地址，写在外置的规则文件里就可以了，而且自定义程度更高。

**Comment by Bourshevik0** [comment]
另外如果大佬做了这个功能的支持，其实就没必要再做ssr之类工具的支持了，只需要让x2tap把流量转发到对应的本地工具的本地代理端口就可以了。

**Comment by hacking001** [comment]
听你这么一讲，我需要加入下面两个功能是么？

**Comment by hacking001** [comment]
全局例外 IP 加了，还差一个 Socks5

白天加功能
晚上研究 C++ DLL 如何在 C# 里调用去了 ...

**Comment by hacking001** [comment]
[当前最新](https://github.com/hacking001/x2tap/releases/tag/1.0.0-BETA)的 release 已经增加了 Socks5 的支持

最新的版本我完全重写了并做了很多的优化，现在 启动、停止 都能做到秒级的

但是很遗憾，全局绕过 IP 的功能我又没加上

这个 issue 将很快关闭（因为我将在近期加上全局绕过 IP 的功能）

**Comment by hacking001** [comment]
此 issue 可以关闭了

已经在 [1d0c979](https://github.com/hacking001/x2tap/commit/1d0c97940227b0659b711a0bcb44234dcefb2007) 中加入的全局绕过 IP 的功能

暂时不准备发 releases 中，如果需要体验，请手动编译

测试通过
