### ISSUE TITLE
能否加个aes 256 ctr

### ISSUE THREAD

**Issue by youtiaoguagua** [hacking001/x2tap#8]

**Comment by hacking001** [comment]
Shadowsocks ？
ShadowsocksR ？
V2Ray ？

**Comment by youtiaoguagua** [comment]
ssr

**Comment by hacking001** [comment]
抱歉，有支持的，忘记加了


明天安排一下！

**Comment by hacking001** [comment]
新版本已发布：[0.1.7-TESTING](https://github.com/hacking001/x2tap/releases/tag/0.1.7-TESTING)
